# Managed by ~/dev/bebbs/dotfiles — edit there, not here.
#
# Everything below is guarded, so a fresh machine (or a half-finished
# bin/setup) gets a working shell instead of a screenful of errors.

export LANG="en_GB.UTF-8"
export LC_ALL="en_GB.UTF-8"
export EDITOR="vim"

# --- Homebrew ---------------------------------------------------------------
# shellenv sets PATH, MANPATH and INFOPATH. Apple Silicon first, then Intel.
for _brew in /opt/homebrew /usr/local; do
  if [[ -x "$_brew/bin/brew" ]]; then
    eval "$("$_brew/bin/brew" shellenv)"
    export HOMEBREW_PREFIX="$_brew"
    break
  fi
done
unset _brew

# --- PATH -------------------------------------------------------------------
# Later calls win, so the order here is lowest to highest priority. Directories
# that don't exist are skipped, which is what keeps a half-set-up machine quiet.
#
# These run after brew shellenv, so ~/.local/bin and ~/bin take precedence over
# $HOMEBREW_PREFIX/bin: a tool installed by both uv and brew resolves to uv's.
prepend_path() { [[ -d "$1" ]] && export PATH="$1:$PATH" }

prepend_path "$HOME/.local/bin"
prepend_path "$HOME/bin"
prepend_path "$HOMEBREW_PREFIX/opt/libpq/bin"
prepend_path "$HOME/dev/bin"
prepend_path "$HOME/dev/dev-environment/bin"

# GNU coreutils/findutils/sed ahead of the BSD versions macOS ships
prepend_path "$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin"
prepend_path "$HOMEBREW_PREFIX/opt/findutils/libexec/gnubin"
prepend_path "$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin"

# --- Oh-My-Zsh --------------------------------------------------------------
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="af-magic"

plugins=(
  git
  emoji
  zsh-syntax-highlighting
  zsh-autosuggestions
)

[[ -d "$ZSH" ]] && source "$ZSH/oh-my-zsh.sh"

# --- Local config -----------------------------------------------------------
# .secrets is generated by bin/secrets and is never committed.
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"
[[ -f "$HOME/.secrets" ]] && source "$HOME/.secrets"

# --- Language runtimes ------------------------------------------------------
command -v rbenv >/dev/null && eval "$(rbenv init - zsh)"

export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"

export BUN_INSTALL="$HOME/.bun"
prepend_path "$BUN_INSTALL/bin"
[[ -s "$BUN_INSTALL/_bun" ]] && source "$BUN_INSTALL/_bun"

# uv / pipx shims
[[ -f "$HOME/.local/bin/env" ]] && source "$HOME/.local/bin/env"

# --- Misc tools -------------------------------------------------------------
command -v zoxide >/dev/null && eval "$(zoxide init zsh)"

# --- Keybindings ------------------------------------------------------------
bindkey "^[[1;3C" forward-word   # alt-right
bindkey "^[[1;3D" backward-word  # alt-left

# --- History ----------------------------------------------------------------
HISTFILE="$HOME/.zsh_history"
HISTSIZE=5000
SAVEHIST=$HISTSIZE
setopt appendhistory sharehistory
setopt hist_ignore_space hist_ignore_all_dups hist_save_no_dups hist_ignore_dups hist_find_no_dups

unsetopt nomatch

# --- Work overlay -----------------------------------------------------------
# Stowed from the carwow/ package, so it only exists on a work machine.
[[ -f "$HOME/.zshrc.work" ]] && source "$HOME/.zshrc.work"
